require("plugins.lazy")
require("plugins.navigation")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.autocomplete")
require("plugins.autoformat")
require("plugins.lint")
require("plugins.notebooks")

require("hugo.set")
require("hugo.remap")
