require("hugo.set")
require("hugo.remap")

require("plugins.lazy")
require("plugins.comment")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.autocomplete")
require("plugins.autoformat")
require("plugins.lint")
