[paths]
schema = relational_schema.sql
logging_config = logging_config.toml

[main]
product_ids=3400935281739;3400934155178;3400934155178
pharmacy_ids=2017412;2035080;2136217

[database]
host = localhost
admin_dbname = postgres
dbname = prediction_commandes
user = python_admin
password = python_admin
port = 5433

[modeling]
basic_models = Naive;SeasonalNaive;SeasESOpt
arima_params = 202100;202101;212000
metrics = mape;rmse;mase;mae
horizons = 1;5;10;20
seasonality = 52
