[loggers]
keys=root,main,database_loading,database_pull,stats,modeling

[handlers]
keys=root_handler,main_stdout,database_loading_file,database_loading_stdout,database_pull_file,database_pull_stdout,stats_stdout,modeling_stdout,modeling_file

[formatters]
keys=formatter



# LOGGERS
[logger_root]
level=NOTSET
handlers=root_handler

[logger_main]
level=DEBUG
handlers=main_stdout
propagate=0
qualname=main

[logger_database_loading]
level=DEBUG
handlers=database_loading_file,database_loading_stdout
propagate=0
qualname=database_loading

[logger_database_pull]
level=DEBUG
handlers=database_pull_file,database_pull_stdout
propagate=0
qualname=database_pull

[logger_stats]
level=INFO
handlers=stats_stdout
propagate=0
qualname=stats

[logger_modeling]
level=DEBUG
handlers=modeling_file,modeling_stdout
propagate=0
qualname=modeling



# HANDLERS
[handler_root_handler]
class=FileHandler
level=DEBUG
formatter=formatter
args=('logs/root.log',)

[handler_main_stdout]
class=StreamHandler
level=DEBUG
formatter=formatter

[handler_database_loading_file]
class=FileHandler
level=WARNING
formatter=formatter
args=('logs/database_loading.log',)

[handler_database_loading_stdout]
class=StreamHandler
level=DEBUG
formatter=formatter

[handler_database_pull_file]
class=FileHandler
level=WARNING
formatter=formatter
args=('logs/database_pull.log',)

[handler_database_pull_stdout]
class=StreamHandler
level=DEBUG
formatter=formatter

[handler_stats_stdout]
class=StreamHandler
level=DEBUG
formatter=formatter

[handler_modeling_file]
class=FileHandler
level=WARNING
formatter=formatter
args=('logs/modeling.log',)

[handler_modeling_stdout]
class=StreamHandler
level=DEBUG
formatter=formatter



# FORMATTERS
[formatter_formatter]
format=%(asctime)s %(name)s %(levelname)s %(message)s
datefmt=
style=%
