require('telescope').load_extension('fzf')
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>na', builtin.find_files, {})
vim.keymap.set('n', '<leader>nw', builtin.live_grep, {})
vim.keymap.set('n', '<leader>nf', builtin.git_files, {})
